name: Release Debian Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.x'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y reprepro gnupg

      - name: Setup GPG Key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --import
          gpg --export -a "${{ secrets.GPG_KEY_ID }}" > public.key

      - name: Create Debian Package Structure
        run: |
          mkdir -p debian/crobrew/DEBIAN
          mkdir -p debian/crobrew/usr/bin
          cat > debian/crobrew/DEBIAN/control << EOF
          Package: crobrew
          Version: ${GITHUB_REF_NAME#v}
          Section: utils
          Priority: optional
          Architecture: ${{ matrix.arch }}
          Maintainer: Chersbobers <chazington7@gmail.com>
          Description: A Simple, Lightweight package manager
           Crobrew is a package manager that supports multiple
           package management systems across different platforms.
          Depends: golang-go
          EOF

      - name: Build Binary
        run: |
          GOOS=linux GOARCH=${{ matrix.arch == 'amd64' && 'amd64' || 'arm64' }} go build -o debian/crobrew/usr/bin/cro

      - name: Build Debian Package
        run: |
          chmod 755 debian/crobrew/usr/bin/cro
          chmod -R 755 debian/crobrew/DEBIAN
          dpkg-deb --build debian/crobrew
          mv debian/crobrew.deb crobrew_${GITHUB_REF_NAME#v}_${{ matrix.arch }}.deb

      - name: Setup APT Repository
        run: |
          mkdir -p apt/conf
          cat > apt/conf/distributions << EOF
          Origin: Crobrew
          Label: Crobrew
          Codename: stable
          Architectures: amd64 arm64
          Components: main
          SignWith: ${{ secrets.GPG_KEY_ID }}
          EOF

          reprepro -b apt includedeb stable crobrew_${GITHUB_REF_NAME#v}_${{ matrix.arch }}.deb

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apt
          force_orphan: true
